### PR TITLE
[WIP] Integrate chartkick

### PR DESCRIPTION
**Pull request by matthiasbeyer**

### CODE REVIEW

**Comment by matthiasbeyer** [comment]
This is much more complicated than I initially thought.

Anyways, I will write tests for it and then refactor it so it is fast/scaleable and clean Ruby anyways... well ... we'll see...

**Comment by matthiasbeyer** [comment]
@TheNeikos I think you have to show me how to write tests (FactoryGirl things, actually) so I can test this...

**Comment by matthiasbeyer** [comment]
@TheNeikos I'm ready here and I'd apprechiate feedback. It works as expected, but I want to add tests for this anyways!

**Comment by TheNeikos** [comment]
I have to admit I don't know what chartkick expects nor what you want to test

**Comment by matthiasbeyer** [comment]
@TheNeikos It expects either a Hash `{ <date> -> <data> }` where `<data>` can be an array or an `Numeric` or the return value of a Hash like on which `#to_a` was called.

**Pull request merged**
